service: <%=chatbotName%>-chatbot-ui
runtime: nodejs10
entrypoint: node app.js
env_variables:
  NODE_ENV: {NODE_ENV}
  DEBUG: false
  GOOGLE_CLIENT_EMAIL: {GOOGLE_CLIENT_EMAIL} 
  GOOGLE_PROJECT_ID: {GOOGLE_PROJECT_ID}
  DIALOGFLOW_SESSION_ID: {DIALOGFLOW_SESSION_ID}
  DIALOGFLOW_SESSION_LANGUAGE_CODE: {DIALOGFLOW_SESSION_LANGUAGE_CODE}
  TWILIO_ACCOUNT_SID: {TWILIO_ACCOUNT_SID}
  TWILIO_FLEX_FLOW_SID: {TWILIO_FLEX_FLOW_SID}
  TWILIO_FLEX_CHAT_SERVICE: {TWILIO_FLEX_CHAT_SERVICE}
  TWILIO_AUTH_TOKEN: {TWILIO_AUTH_TOKEN}
  TWILIO_API_KEY: {TWILIO_API_KEY}
  TWILIO_API_SECRET: {TWILIO_API_SECRET}
handlers:
- url: /(.*\.(gif|png|jpg|svg|js|css|map|json|tff|woff))$
  secure: always
  static_files: build/\1
  upload: build/(.*\..+)$
- url: /
  secure: always
  static_files: build/index.html
  upload: build/index.html
- url: /.*
  secure: always
  script: auto
